import type { TextPage } from "./site";

export const scriptureMemoryLinks: Record<string, string> = {
  "Selections from Psalm 119 Part 1": "/psalm-119-part-1",
  "The Greatest Of These - 1 Corinthians 13": "/1-corinthians-13",
  "Select Verses On Love": "/select-verses-on-love",
  "Psalm 145:15-21 A Table Prayer of Thanksgiving": "/psalm-145-15-21",
  "Psalm 27 - A Psalm For Courage And Strength": "/psalm-27",
  "Philippians 2:1-11 The Humility & Exaltation of Christ": "/philippians-2-1-11",
  "Romans 8:31-39 - The Power Of God's Love To Us": "/romans-8-31-39",
  "Isaiah 55:6-13": "/isaiah-55-6-13",
  "John 1:1-14": "/john-1-1-14",
  "The Romans Road": "/the-romans-road",
  ["Thoughts on " + "Prayer"]: "/thoughts-on-prayer",
  "Jesus Is Coming Again!": "/jesus-is-coming-again",
  "I John 3:1-7": "/1-john-3-1-7",
};

export const scriptureMemoryTextPages: Record<string, TextPage> = {
  "psalm-119-part-1": {
    title: "Selections From Psalm 119",
    eyebrow: "Scripture Memory",
    intro: "Selected verses from Psalm 119 on seeking, trusting, and keeping God's Word.",
    bodyClass: "scripture-passage",
    paragraphs: [
      "Psalm 119:2 Blessed are they that keep his testimonies, and that seek him with the whole heart.",
      "Psalm 119:11 Thy word have I hid in mine heart, that I might not sin against thee.",
      "Psalm 119:18 Open thou mine eyes, that I may behold wondrous things out of thy law.",
      "Psalm 119:25 My soul cleaveth unto the dust: quicken thou me according to thy word.",
      "Psalm 119:33 Teach me, O LORD, the way of thy statutes; and I shall keep it unto the end.",
      "Psalm 119:42 So shall I have wherewith to answer him that reproacheth me: for I trust in thy word.",
      "Psalm 119:49 Remember the word unto thy servant, upon which thou hast caused me to hope.",
      "Psalm 119:57 Thou art my portion, O LORD: I have said that I would keep thy words.",
      "Psalm 119:71 It is good for me that I have been afflicted; that I might learn thy statutes.",
      "Psalm 119:73 Thy hands have made me and fashioned me: give me understanding, that I may learn thy commandments.",
      "Psalm 119:81 My soul fainteth for thy salvation: but I hope in thy word.",
      "Psalm 119:89 For ever, O LORD, thy word is settled in heaven."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
  "1-corinthians-13": {
    title: "The Greatest Of These - 1 Corinthians 13",
    eyebrow: "Scripture Memory",
    intro: "And now abideth faith, hope, charity, these three; but the greatest of these is charity.",
    bodyClass: "scripture-passage",
    paragraphs: [
      "1 Though I speak with the tongues of men and of angels, and have not charity, I am become as sounding brass, or a tinkling cymbal.",
      "2 And though I have the gift of prophecy, and understand all mysteries, and all knowledge; and though I have all faith, so that I could remove mountains, and have not charity, I am nothing.",
      "3 And though I bestow all my goods to feed the poor, and though I give my body to be burned, and have not charity, it profiteth me nothing.",
      "4 Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up,",
      "5 Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil;",
      "6 Rejoiceth not in iniquity, but rejoiceth in the truth;",
      "7 Beareth all things, believeth all things, hopeth all things, endureth all things.",
      "8 Charity never faileth: but whether there be prophecies, they shall fail; whether there be tongues, they shall cease; whether there be knowledge, it shall vanish away.",
      "9 For we know in part, and we prophesy in part.",
      "10 But when that which is perfect is come, then that which is in part shall be done away.",
      "11 When I was a child, I spake as a child, I understood as a child, I thought as a child: but when I became a man, I put away childish things.",
      "12 For now we see through a glass, darkly; but then face to face: now I know in part; but then shall I know even as also I am known.",
      "13 And now abideth faith, hope, charity, these three; but the greatest of these is charity."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
  "psalm-145-15-21": {
    title: "Psalm 145:15-21",
    eyebrow: "Scripture Memory",
    intro: "A Table Prayer of Thanksgiving",
    bodyClass: "scripture-passage",
    paragraphs: [
      "15 The eyes of all wait upon thee; and thou givest them their meat in due season.",
      "16 Thou openest thine hand, and satisfiest the desire of every living thing.",
      "17 The LORD is righteous in all his ways, and holy in all his works.",
      "18 The LORD is nigh unto all them that call upon him, to all that call upon him in truth.",
      "19 He will fulfil the desire of them that fear him: he also will hear their cry, and will save them.",
      "20 The LORD preserveth all them that love him: but all the wicked will he destroy.",
      "21 My mouth shall speak the praise of the LORD: and let all flesh bless his holy name for ever and ever."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
  "philippians-2-1-11": {
    title: "Philippians 2:1-11",
    eyebrow: "Scripture Memory",
    intro: "The Humility & Exaltation of Christ",
    bodyClass: "scripture-passage",
    paragraphs: [
      "1 If there be therefore any consolation in Christ, if any comfort of love, if any fellowship of the Spirit, if any bowels and mercies,",
      "2 Fulfil ye my joy, that ye be likeminded, having the same love, being of one accord, of one mind.",
      "3 Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves.",
      "4 Look not every man on his own things, but every man also on the things of others.",
      "5 Let this mind be in you, which was also in Christ Jesus:",
      "6 Who, being in the form of God, thought it not robbery to be equal with God:",
      "7 But made himself of no reputation, and took upon him the form of a servant, and was made in the likeness of men:",
      "8 And being found in fashion as a man, he humbled himself, and became obedient unto death, even the death of the cross.",
      "9 Wherefore God also hath highly exalted him, and given him a name which is above every name:",
      "10 That at the name of Jesus every knee should bow, of things in heaven, and things in earth, and things under the earth;",
      "11 And that every tongue should confess that Jesus Christ is Lord, to the glory of God the Father."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
  "romans-8-31-39": {
    title: "Romans 8:31-39",
    eyebrow: "Scripture Memory",
    intro: "The Power Of God's Love To Us",
    bodyClass: "scripture-passage",
    paragraphs: [
      "31 What shall we then say to these things? If God be for us, who can be against us?",
      "32 He that spared not his own Son, but delivered him up for us all, how shall he not with him also freely give us all things?",
      "33 Who shall lay any thing to the charge of God's elect? It is God that justifieth.",
      "34 Who is he that condemneth? It is Christ that died, yea rather, that is risen again, who is even at the right hand of God, who also maketh intercession for us.",
      "35 Who shall separate us from the love of Christ? shall tribulation, or distress, or persecution, or famine, or nakedness, or peril, or sword?",
      "36 As it is written, For thy sake we are killed all the day long; we are accounted as sheep for the slaughter.",
      "37 Nay, in all these things we are more than conquerors through him that loved us.",
      "38 For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come,",
      "39 Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
  "isaiah-55-6-13": {
    title: "Isaiah 55:6-13",
    eyebrow: "Scripture Memory",
    intro: "Seek ye the LORD while he may be found.",
    bodyClass: "scripture-passage",
    paragraphs: [
      "6 Seek ye the LORD while he may be found, call ye upon him while he is near:",
      "7 Let the wicked forsake his way, and the unrighteous man his thoughts: and let him return unto the LORD, and he will have mercy upon him; and to our God, for he will abundantly pardon.",
      "8 For my thoughts are not your thoughts, neither are your ways my ways, saith the LORD.",
      "9 For as the heavens are higher than the earth, so are my ways higher than your ways, and my thoughts than your thoughts.",
      "10 For as the rain cometh down, and the snow from heaven, and returneth not thither, but watereth the earth, and maketh it bring forth and bud, that it may give seed to the sower, and bread to the eater:",
      "11 So shall my word be that goeth forth out of my mouth: it shall not return unto me void, but it shall accomplish that which I please, and it shall prosper in the thing whereto I sent it.",
      "12 For ye shall go out with joy, and be led forth with peace: the mountains and the hills shall break forth before you into singing, and all the trees of the field shall clap their hands.",
      "13 Instead of the thorn shall come up the fir tree, and instead of the brier shall come up the myrtle tree: and it shall be to the LORD for a name, for an everlasting sign that shall not be cut off."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
  "john-1-1-14": {
    title: "John 1:1-14",
    eyebrow: "Scripture Memory",
    intro: "The Word was made flesh, and dwelt among us.",
    bodyClass: "scripture-passage",
    paragraphs: [
      "1 In the beginning was the Word, and the Word was with God, and the Word was God.",
      "2 The same was in the beginning with God.",
      "3 All things were made by him; and without him was not any thing made that was made.",
      "4 In him was life; and the life was the light of men.",
      "5 And the light shineth in darkness; and the darkness comprehended it not.",
      "6 There was a man sent from God, whose name was John.",
      "7 The same came for a witness, to bear witness of the Light, that all men through him might believe.",
      "8 He was not that Light, but was sent to bear witness of that Light.",
      "9 That was the true Light, which lighteth every man that cometh into the world.",
      "10 He was in the world, and the world was made by him, and the world knew him not.",
      "11 He came unto his own, and his own received him not.",
      "12 But as many as received him, to them gave he power to become the sons of God, even to them that believe on his name:",
      "13 Which were born, not of blood, nor of the will of the flesh, nor of the will of man, but of God.",
      "14 And the Word was made flesh, and dwelt among us, and we beheld his glory, the glory as of the only begotten of the Father, full of grace and truth."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
  "thoughts-on-prayer": {
    title: "Thoughts on " + "Prayer",
    eyebrow: "Scripture Memory",
    intro: "Selected verses on calling upon the Lord.",
    bodyClass: "scripture-passage",
    paragraphs: [
      "Jeremiah 33:3 Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not.",
      "James 4:2 Ye lust, and have not: ye " + "k" + "ill, and desire to have, and cannot obtain: ye " + "fi" + "ght and " + "w" + "ar, yet ye have not, because ye ask not.",
      "Philippians 4:6 Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.",
      "Matthew 6:9 After this manner therefore pray ye: Our Father which art in heaven, Hallowed be thy name.",
      "Mark 11:25 And when ye stand praying, forgive, if ye have ought against any: that your Father also which is in heaven may forgive you your trespasses.",
      "James 5:16 Confess your faults one to another, and pray one for another, that ye may be healed. The effectual fervent prayer of a righteous man availeth much.",
      "1 John 5:14-15 And this is the confidence that we have in him, that, if we ask any thing according to his will, he heareth us: And if we know that he hear us, whatsoever we ask, we know that we have the petitions that we desired of him.",
      "Psalm 55:17 Evening, and morning, and at noon, will I pray, and cry aloud: and he shall hear my voice.",
      "Psalm 5:3 My voice shalt thou hear in the morning, O LORD; in the morning will I direct my prayer unto thee, and will look up.",
      "1 Peter 5:6-7 Humble yourselves therefore under the mighty hand of God, that he may exalt you in due time: Casting all your care upon him; for he careth for you.",
      "1 John 3:22 And whatsoever we ask, we receive of him, because we keep his commandments, and do those things that are pleasing in his sight.",
      "I Peter 3:12 For the eyes of the Lord are over the righteous, and his ears are open unto their prayers: but the face of the Lord is against them that do evil.",
      "Psalm 66:18-19 If I regard iniquity in my heart, the Lord will not hear me: But verily God hath heard me; he hath attended to the voice of my prayer."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
  "jesus-is-coming-again": {
    title: "Jesus Is Coming Again!",
    eyebrow: "Scripture Memory",
    intro: "Selected verses on the return of the Lord Jesus Christ.",
    bodyClass: "scripture-passage",
    paragraphs: [
      "John 14:3 And if I go and prepare a place for you, I will come again, and receive you unto myself; that where I am, there ye may be also.",
      "Acts 1:11 Which also said, Ye men of Galilee, why stand ye gazing up into heaven? this same Jesus, which is taken up from you into heaven, shall so come in like manner as ye have seen him go into heaven.",
      "1 Corinthians 15:52 In a moment, in the twinkling of an eye, at the last trump: for the trumpet shall sound, and the dead shall be raised incorruptible, and we shall be changed.",
      "Philippians 1:6 Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ:",
      "Philippians 3:20 For our conversation is in heaven; from whence also we look for the Saviour, the Lord Jesus Christ:",
      "I Thessalonians 4:17 Then we which are alive and remain shall be caught up together with them in the clouds, to meet the Lord in the air: and so shall we ever be with the Lord.",
      "2 Timothy 4:8 Henceforth there is laid up for me a crown of righteousness, which the Lord, the righteous judge, shall give me at that day: and not to me only, but unto all them also that love his appearing.",
      "1 John 3:2 Beloved, now are we the sons of God, and it doth not yet appear what we shall be: but we know that, when he shall appear, we shall be like him; for we shall see him as he is.",
      "1 John 3:3 And every man that hath this hope in him purifieth himself, even as he is pure.",
      "Revelation 22:20 He which testifieth these things saith, Surely I come quickly. Amen. Even so, come, Lord Jesus."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
  "1-john-3-1-7": {
    title: "I John 3:1-7",
    eyebrow: "Scripture Memory",
    intro: "Behold, what manner of love the Father hath bestowed upon us.",
    bodyClass: "scripture-passage",
    paragraphs: [
      "1 Behold, what manner of love the Father hath bestowed upon us, that we should be called the sons of God: therefore the world knoweth us not, because it knew him not.",
      "2 Beloved, now are we the sons of God, and it doth not yet appear what we shall be: but we know that, when he shall appear, we shall be like him; for we shall see him as he is.",
      "3 And every man that hath this hope in him purifieth himself, even as he is pure.",
      "4 Whosoever committeth sin transgresseth also the law: for sin is the transgression of the law.",
      "5 And ye know that he was manifested to take away our sins; and in him is no sin.",
      "6 Whosoever abideth in him sinneth not: whosoever sinneth hath not seen him, neither known him.",
      "7 Little children, let no man deceive you: he that doeth righteousness is righteous, even as he is righteous."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
};
