import type { TextPage } from "./site";

export const scriptureMemoryLinks: Record<string, string> = {
  "The Greatest of These: I Corinthians 13": "/1-corinthians-13",
  "Psalm 145:15-21 A Table Prayer of Thanksgiving": "/psalm-145-15-21",
  "Psalm 27 - A Psalm For Courage And Strength": "/psalm-27",
  "Philippians 2:1-11 The Humility & Exaltation of Christ": "/philippians-2-1-11",
  "Romans 8:31-39 - The Power Of God's Love To Us": "/romans-8-31-39",
  "Isaiah 55:6-13": "/isaiah-55-6-13",
  "John 1:1-14": "/john-1-1-14",
  "The Romans Road": "/the-romans-road",
  "I John 3:1-7": "/1-john-3-1-7",
};

export const scriptureMemoryTextPages: Record<string, TextPage> = {
  "1-corinthians-13": {
    title: "The Greatest of These: I Corinthians 13",
    eyebrow: "Scripture Memory",
    intro: "And now abideth faith, hope, charity, these three; but the greatest of these is charity.",
    bodyClass: "scripture-passage",
    paragraphs: [
      "1 Though I speak with the tongues of men and of angels, and have not charity, I am become as sounding brass, or a tinkling cymbal.",
      "2 And though I have the gift of prophecy, and understand all mysteries, and all knowledge; and though I have all faith, so that I could remove mountains, and have not charity, I am nothing.",
      "3 And though I bestow all my goods to feed the poor, and though I give my body to be burned, and have not charity, it profiteth me nothing.",
      "4 Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up,",
      "5 Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil;",
      "6 Rejoiceth not in iniquity, but rejoiceth in the truth;",
      "7 Beareth all things, believeth all things, hopeth all things, endureth all things.",
      "8 Charity never faileth: but whether there be prophecies, they shall fail; whether there be tongues, they shall cease; whether there be knowledge, it shall vanish away.",
      "9 For we know in part, and we prophesy in part.",
      "10 But when that which is perfect is come, then that which is in part shall be done away.",
      "11 When I was a child, I spake as a child, I understood as a child, I thought as a child: but when I became a man, I put away childish things.",
      "12 For now we see through a glass, darkly; but then face to face: now I know in part; but then shall I know even as also I am known.",
      "13 And now abideth faith, hope, charity, these three; but the greatest of these is charity."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
  "psalm-145-15-21": {
    title: "Psalm 145:15-21",
    eyebrow: "Scripture Memory",
    intro: "A Table Prayer of Thanksgiving",
    bodyClass: "scripture-passage",
    paragraphs: [
      "15 The eyes of all wait upon thee; and thou givest them their meat in due season.",
      "16 Thou openest thine hand, and satisfiest the desire of every living thing.",
      "17 The LORD is righteous in all his ways, and holy in all his works.",
      "18 The LORD is nigh unto all them that call upon him, to all that call upon him in truth.",
      "19 He will fulfil the desire of them that fear him: he also will hear their cry, and will save them.",
      "20 The LORD preserveth all them that love him: but all the wicked will he destroy.",
      "21 My mouth shall speak the praise of the LORD: and let all flesh bless his holy name for ever and ever."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
  "philippians-2-1-11": {
    title: "Philippians 2:1-11",
    eyebrow: "Scripture Memory",
    intro: "The Humility & Exaltation of Christ",
    bodyClass: "scripture-passage",
    paragraphs: [
      "1 If there be therefore any consolation in Christ, if any comfort of love, if any fellowship of the Spirit, if any bowels and mercies,",
      "2 Fulfil ye my joy, that ye be likeminded, having the same love, being of one accord, of one mind.",
      "3 Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves.",
      "4 Look not every man on his own things, but every man also on the things of others.",
      "5 Let this mind be in you, which was also in Christ Jesus:",
      "6 Who, being in the form of God, thought it not robbery to be equal with God:",
      "7 But made himself of no reputation, and took upon him the form of a servant, and was made in the likeness of men:",
      "8 And being found in fashion as a man, he humbled himself, and became obedient unto death, even the death of the cross.",
      "9 Wherefore God also hath highly exalted him, and given him a name which is above every name:",
      "10 That at the name of Jesus every knee should bow, of things in heaven, and things in earth, and things under the earth;",
      "11 And that every tongue should confess that Jesus Christ is Lord, to the glory of God the Father."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
  "romans-8-31-39": {
    title: "Romans 8:31-39",
    eyebrow: "Scripture Memory",
    intro: "The Power Of God's Love To Us",
    bodyClass: "scripture-passage",
    paragraphs: [
      "31 What shall we then say to these things? If God be for us, who can be against us?",
      "32 He that spared not his own Son, but delivered him up for us all, how shall he not with him also freely give us all things?",
      "33 Who shall lay any thing to the charge of God's elect? It is God that justifieth.",
      "34 Who is he that condemneth? It is Christ that died, yea rather, that is risen again, who is even at the right hand of God, who also maketh intercession for us.",
      "35 Who shall separate us from the love of Christ? shall tribulation, or distress, or persecution, or famine, or nakedness, or peril, or sword?",
      "36 As it is written, For thy sake we are killed all the day long; we are accounted as sheep for the slaughter.",
      "37 Nay, in all these things we are more than conquerors through him that loved us.",
      "38 For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come,",
      "39 Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
  "isaiah-55-6-13": {
    title: "Isaiah 55:6-13",
    eyebrow: "Scripture Memory",
    intro: "Seek ye the LORD while he may be found.",
    bodyClass: "scripture-passage",
    paragraphs: [
      "6 Seek ye the LORD while he may be found, call ye upon him while he is near:",
      "7 Let the wicked forsake his way, and the unrighteous man his thoughts: and let him return unto the LORD, and he will have mercy upon him; and to our God, for he will abundantly pardon.",
      "8 For my thoughts are not your thoughts, neither are your ways my ways, saith the LORD.",
      "9 For as the heavens are higher than the earth, so are my ways higher than your ways, and my thoughts than your thoughts.",
      "10 For as the rain cometh down, and the snow from heaven, and returneth not thither, but watereth the earth, and maketh it bring forth and bud, that it may give seed to the sower, and bread to the eater:",
      "11 So shall my word be that goeth forth out of my mouth: it shall not return unto me void, but it shall accomplish that which I please, and it shall prosper in the thing whereto I sent it.",
      "12 For ye shall go out with joy, and be led forth with peace: the mountains and the hills shall break forth before you into singing, and all the trees of the field shall clap their hands.",
      "13 Instead of the thorn shall come up the fir tree, and instead of the brier shall come up the myrtle tree: and it shall be to the LORD for a name, for an everlasting sign that shall not be cut off."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
  "john-1-1-14": {
    title: "John 1:1-14",
    eyebrow: "Scripture Memory",
    intro: "The Word was made flesh, and dwelt among us.",
    bodyClass: "scripture-passage",
    paragraphs: [
      "1 In the beginning was the Word, and the Word was with God, and the Word was God.",
      "2 The same was in the beginning with God.",
      "3 All things were made by him; and without him was not any thing made that was made.",
      "4 In him was life; and the life was the light of men.",
      "5 And the light shineth in darkness; and the darkness comprehended it not.",
      "6 There was a man sent from God, whose name was John.",
      "7 The same came for a witness, to bear witness of the Light, that all men through him might believe.",
      "8 He was not that Light, but was sent to bear witness of that Light.",
      "9 That was the true Light, which lighteth every man that cometh into the world.",
      "10 He was in the world, and the world was made by him, and the world knew him not.",
      "11 He came unto his own, and his own received him not.",
      "12 But as many as received him, to them gave he power to become the sons of God, even to them that believe on his name:",
      "13 Which were born, not of blood, nor of the will of the flesh, nor of the will of man, but of God.",
      "14 And the Word was made flesh, and dwelt among us..."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
  "1-john-3-1-7": {
    title: "I John 3:1-7",
    eyebrow: "Scripture Memory",
    intro: "Behold, what manner of love the Father hath bestowed upon us.",
    bodyClass: "scripture-passage",
    paragraphs: [
      "1 Behold, what manner of love the Father hath bestowed upon us, that we should be called the sons of God...",
      "2 Beloved, now are we the sons of God, and it doth not yet appear what we shall be...",
      "3 And every man that hath this hope in him purifieth himself, even as he is pure.",
      "4 Whosoever committeth sin transgresseth also the law: for sin is the transgression of the law.",
      "5 And ye know that he was manifested to take away our sins; and in him is no sin.",
      "6 Whosoever abideth in him sinneth not: whosoever sinneth hath not seen him, neither known him.",
      "7 Little children, let no man deceive you: he that doeth righteousness is righteous, even as he is righteous."
    ],
    cta: ["Back to Scripture Memory", "/scripture-memory-1"],
  },
};
